# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/fpga14/fpga_14_all/project_2/Nexys-A7-100T-Master.xdc

# XDC: /home/fpga14/fpga_14_all/project_2/floorplan.xdc

# XDC: /home/fpga14/fpga_14_all/project_2/timing.xdc

# IP: ip/cordic_0_1/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet
