# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/sqrt_cordic/sqrt_cordic.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sqrt_cordic || ORIG_REF_NAME==sqrt_cordic} -quiet] -quiet
